version: '3.8'
services:
  pagatracks:
    build: .
    container_name: pagatracks-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true