export const texts = {
  createNewRoute: "Create new route",
  deleteRouteHint: "Delete route",
  designRoute: "Design route",
  downloadRouteHint: "Download route",
  elevation: "elevation",
  firstAddTrack: "First add a track",
  paved: "Paved",
  selectNextTrack: "Select next track",
  selectStartingPoint: "Select starting point",
  singleTrack: "Singletrack",
  undoRouteHint: "Undo",
  unpaved: "Unpaved",
  yourRoute: "Your route",
};
